version: "3.2"
services:
  server:
    image: ${APP_NAME}-server:latest
    deploy:
      replicas: 1
    ports:
      - "${TEST_STACK_PORT}:80"
    networks:
      - public-network
networks:
  public-network:
    internal: false
