APP_NAME=$(basename "$(cd "$(dirname "$BASH_SOURCE")"/.. && pwd)")
DEV_PORT=$EXAMPLE_DEV_PORT
DEV_STACK_PORT=$EXAMPLE_DEV_STACK_PORT
TEST_STACK_PORT=$EXAMPLE_TEST_STACK_PORT
DEV_STACK=$APP_NAME-dev
TEST_STACK=$APP_NAME
REGISTRY=registry.example.com
